"""add user_info and other models

Revision ID: 155b936a0c47
Revises: f0be1eddb59f
Create Date: 2023-03-03 22:22:04.557776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155b936a0c47'
down_revision = 'f0be1eddb59f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
