"""add user_info and other models

Revision ID: 4b554ef49098
Revises: c542bf42021a
Create Date: 2023-03-03 22:11:41.244694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b554ef49098'
down_revision = 'c542bf42021a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
