"""add user_info and other models

Revision ID: 52111e08d684
Revises: a7a36bbb4d44
Create Date: 2023-03-07 09:14:45.112391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52111e08d684'
down_revision = 'a7a36bbb4d44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
