"""add user_info and other models

Revision ID: 592c546d5186
Revises: 52111e08d684
Create Date: 2023-03-07 09:19:06.105803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592c546d5186'
down_revision = '52111e08d684'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('project_logo', sa.String(), nullable=True),
    sa.Column('full_description', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_info.info_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_block',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('block_description', sa.String(), nullable=True),
    sa.Column('block_author_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_author_id'], ['user_info.info_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('block_block_m2m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_block_id', sa.Integer(), nullable=True),
    sa.Column('right_block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_block_id'], ['project_block.block_id'], ),
    sa.ForeignKeyConstraint(['right_block_id'], ['project_block.block_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_block_m2m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['project_block.block_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_block_m2m')
    op.drop_table('block_block_m2m')
    op.drop_table('project_block')
    op.drop_table('project')
    # ### end Alembic commands ###
