"""add user_info and other models

Revision ID: 6b9ef269eaaa
Revises: 
Create Date: 2023-03-03 21:49:11.819993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9ef269eaaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_user_m2m', sa.Column('skill_lvl', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_user_m2m', 'skill_lvl')
    # ### end Alembic commands ###
