"""add user_info and other models

Revision ID: 87885bee93ad
Revises: 155b936a0c47
Create Date: 2023-03-04 16:05:49.894897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87885bee93ad'
down_revision = '155b936a0c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
