"""add user_info and other models

Revision ID: 97bf6c9beb8a
Revises: 87885bee93ad
Create Date: 2023-03-05 03:49:23.998139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bf6c9beb8a'
down_revision = '87885bee93ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
