"""add user_info and other models

Revision ID: bdb2cb74a6b2
Revises: 97bf6c9beb8a
Create Date: 2023-03-05 03:58:31.473688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb2cb74a6b2'
down_revision = '97bf6c9beb8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
