"""add user_info and other models

Revision ID: c2193bd40ae9
Revises: 4b554ef49098
Create Date: 2023-03-03 22:16:37.317357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2193bd40ae9'
down_revision = '4b554ef49098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
