"""add email token

Revision ID: c2f99b4c5ee8
Revises: 4772764b0b78
Create Date: 2023-02-25 04:40:21.223752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f99b4c5ee8'
down_revision = '4772764b0b78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_token',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('bearer', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bearer'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('key', name='uix_1')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_token')
    # ### end Alembic commands ###
