"""add user_info and other models

Revision ID: c542bf42021a
Revises: 6b9ef269eaaa
Create Date: 2023-03-03 21:58:11.187727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c542bf42021a'
down_revision = '6b9ef269eaaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
