"""add user_info and other models

Revision ID: cd920a2be5dc
Revises: c2193bd40ae9
Create Date: 2023-03-03 22:19:59.097881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd920a2be5dc'
down_revision = 'c2193bd40ae9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
