"""add user_info and other models

Revision ID: d135e2984118
Revises: bdb2cb74a6b2
Create Date: 2023-03-07 07:09:48.975527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd135e2984118'
down_revision = 'bdb2cb74a6b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('photo_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'photo_link')
    # ### end Alembic commands ###
