"""add user_info and other models

Revision ID: eb8bca3c0f7f
Revises: 592c546d5186
Create Date: 2023-03-08 05:40:00.867281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8bca3c0f7f'
down_revision = '592c546d5186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
