"""add user_info and other models

Revision ID: f0be1eddb59f
Revises: cd920a2be5dc
Create Date: 2023-03-03 22:20:50.195771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0be1eddb59f'
down_revision = 'cd920a2be5dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
