"""add user_info and other models

Revision ID: f1c601898f01
Revises: c2f99b4c5ee8
Create Date: 2023-03-02 03:08:19.933753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c601898f01'
down_revision = 'c2f99b4c5ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('skill_name', name='uix_2')
    )
    op.create_table('user_info',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('link',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.info_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('skill_user_m2m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.info_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_user_m2m')
    op.drop_table('link')
    op.drop_table('user_info')
    op.drop_table('skill')
    # ### end Alembic commands ###
